{"asctime": "10/24/2020 05:08:48 PM", "levelname": "WARNING", "name": "root", "message": "warning"}
{"asctime": "10/24/2020 05:08:48 PM", "levelname": "ERROR", "name": "root", "message": "error"}
{"asctime": "10/24/2020 05:08:48 PM", "levelname": "INFO", "name": "werkzeug", "message": "127.0.0.1 - - [24/Oct/2020 17:08:48] \"GET /demo_logs HTTP/1.1\" 200 -"}
{"asctime": "10/24/2020 05:09:49 PM", "levelname": "DEBUG", "name": "root", "message": "debug"}
{"asctime": "10/24/2020 05:09:49 PM", "levelname": "INFO", "name": "root", "message": "info"}
{"asctime": "10/24/2020 05:09:49 PM", "levelname": "WARNING", "name": "root", "message": "warning"}
{"asctime": "10/24/2020 05:09:49 PM", "levelname": "ERROR", "name": "root", "message": "error"}
{"asctime": "10/24/2020 05:09:49 PM", "levelname": "INFO", "name": "werkzeug", "message": "127.0.0.1 - - [24/Oct/2020 17:09:49] \"GET /demo_logs HTTP/1.1\" 200 -"}
{"asctime": "11/05/2020 11:59:14 PM", "levelname": "ERROR", "name": "routes", "message": "Exception on /link_items [POST]", "exc_info": "Traceback (most recent call last):\n  File \"/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/flask/app.py\", line 2446, in wsgi_app\n    response = self.full_dispatch_request()\n  File \"/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/flask/app.py\", line 1951, in full_dispatch_request\n    rv = self.handle_user_exception(e)\n  File \"/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/flask_cors/extension.py\", line 165, in wrapped_function\n    return cors_after_request(app.make_response(f(*args, **kwargs)))\n  File \"/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/flask/app.py\", line 1820, in handle_user_exception\n    reraise(exc_type, exc_value, tb)\n  File \"/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/flask/_compat.py\", line 39, in reraise\n    raise value\n  File \"/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/flask/app.py\", line 1949, in full_dispatch_request\n    rv = self.dispatch_request()\n  File \"/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/flask/app.py\", line 1935, in dispatch_request\n    return self.view_functions[rule.endpoint](**req.view_args)\n  File \"/Users/ktsutter/Capstone/JamaConnectBackend/server/routes.py\", line 308, in link_items\n    jira_item = data[\"jira_item\"][0]\nKeyError: 'jira_item'"}
{"asctime": "11/05/2020 11:59:14 PM", "levelname": "INFO", "name": "werkzeug", "message": "127.0.0.1 - - [05/Nov/2020 23:59:14] \"POST /link_items HTTP/1.1\" 500 -"}
{"asctime": "11/06/2020 12:00:26 AM", "levelname": "ERROR", "name": "routes", "message": "Exception on /link_items [POST]", "exc_info": "Traceback (most recent call last):\n  File \"/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/flask/app.py\", line 2446, in wsgi_app\n    response = self.full_dispatch_request()\n  File \"/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/flask/app.py\", line 1951, in full_dispatch_request\n    rv = self.handle_user_exception(e)\n  File \"/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/flask_cors/extension.py\", line 165, in wrapped_function\n    return cors_after_request(app.make_response(f(*args, **kwargs)))\n  File \"/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/flask/app.py\", line 1820, in handle_user_exception\n    reraise(exc_type, exc_value, tb)\n  File \"/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/flask/_compat.py\", line 39, in reraise\n    raise value\n  File \"/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/flask/app.py\", line 1949, in full_dispatch_request\n    rv = self.dispatch_request()\n  File \"/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/flask/app.py\", line 1935, in dispatch_request\n    return self.view_functions[rule.endpoint](**req.view_args)\n  File \"/Users/ktsutter/Capstone/JamaConnectBackend/server/routes.py\", line 308, in link_items\n    jira_item = data[\"jira_item\"][0]\nKeyError: 'jira_item'"}
{"asctime": "11/06/2020 12:00:26 AM", "levelname": "INFO", "name": "werkzeug", "message": "127.0.0.1 - - [06/Nov/2020 00:00:26] \"POST /link_items HTTP/1.1\" 500 -"}
{"asctime": "11/06/2020 12:00:58 AM", "levelname": "ERROR", "name": "routes", "message": "Exception on /link_items [POST]", "exc_info": "Traceback (most recent call last):\n  File \"/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/flask/app.py\", line 2446, in wsgi_app\n    response = self.full_dispatch_request()\n  File \"/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/flask/app.py\", line 1951, in full_dispatch_request\n    rv = self.handle_user_exception(e)\n  File \"/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/flask_cors/extension.py\", line 165, in wrapped_function\n    return cors_after_request(app.make_response(f(*args, **kwargs)))\n  File \"/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/flask/app.py\", line 1820, in handle_user_exception\n    reraise(exc_type, exc_value, tb)\n  File \"/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/flask/_compat.py\", line 39, in reraise\n    raise value\n  File \"/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/flask/app.py\", line 1949, in full_dispatch_request\n    rv = self.dispatch_request()\n  File \"/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/flask/app.py\", line 1935, in dispatch_request\n    return self.view_functions[rule.endpoint](**req.view_args)\n  File \"/Users/ktsutter/Capstone/JamaConnectBackend/server/routes.py\", line 308, in link_items\n    jira_item = data[\"jira_item\"][0]\nKeyError: 'jira_item'"}
{"asctime": "11/06/2020 12:00:58 AM", "levelname": "INFO", "name": "werkzeug", "message": "127.0.0.1 - - [06/Nov/2020 00:00:58] \"POST /link_items HTTP/1.1\" 500 -"}
{"asctime": "11/06/2020 12:02:12 AM", "levelname": "ERROR", "name": "routes", "message": "Exception on /link_items [POST]", "exc_info": "Traceback (most recent call last):\n  File \"/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/flask/app.py\", line 2446, in wsgi_app\n    response = self.full_dispatch_request()\n  File \"/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/flask/app.py\", line 1951, in full_dispatch_request\n    rv = self.handle_user_exception(e)\n  File \"/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/flask_cors/extension.py\", line 165, in wrapped_function\n    return cors_after_request(app.make_response(f(*args, **kwargs)))\n  File \"/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/flask/app.py\", line 1820, in handle_user_exception\n    reraise(exc_type, exc_value, tb)\n  File \"/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/flask/_compat.py\", line 39, in reraise\n    raise value\n  File \"/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/flask/app.py\", line 1949, in full_dispatch_request\n    rv = self.dispatch_request()\n  File \"/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/flask/app.py\", line 1935, in dispatch_request\n    return self.view_functions[rule.endpoint](**req.view_args)\n  File \"/Users/ktsutter/Capstone/JamaConnectBackend/server/routes.py\", line 306, in link_items\n    data = dict(request.data)\nTypeError: cannot convert dictionary update sequence element #0 to a sequence"}
{"asctime": "11/06/2020 12:02:12 AM", "levelname": "INFO", "name": "werkzeug", "message": "127.0.0.1 - - [06/Nov/2020 00:02:12] \"POST /link_items HTTP/1.1\" 500 -"}
{"asctime": "11/06/2020 12:02:33 AM", "levelname": "ERROR", "name": "routes", "message": "Exception on /link_items [POST]", "exc_info": "Traceback (most recent call last):\n  File \"/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/flask/app.py\", line 2446, in wsgi_app\n    response = self.full_dispatch_request()\n  File \"/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/flask/app.py\", line 1951, in full_dispatch_request\n    rv = self.handle_user_exception(e)\n  File \"/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/flask_cors/extension.py\", line 165, in wrapped_function\n    return cors_after_request(app.make_response(f(*args, **kwargs)))\n  File \"/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/flask/app.py\", line 1820, in handle_user_exception\n    reraise(exc_type, exc_value, tb)\n  File \"/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/flask/_compat.py\", line 39, in reraise\n    raise value\n  File \"/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/flask/app.py\", line 1949, in full_dispatch_request\n    rv = self.dispatch_request()\n  File \"/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/flask/app.py\", line 1935, in dispatch_request\n    return self.view_functions[rule.endpoint](**req.view_args)\n  File \"/Users/ktsutter/Capstone/JamaConnectBackend/server/routes.py\", line 306, in link_items\n    data = dict(request.get_data())\nTypeError: cannot convert dictionary update sequence element #0 to a sequence"}
{"asctime": "11/06/2020 12:02:33 AM", "levelname": "INFO", "name": "werkzeug", "message": "127.0.0.1 - - [06/Nov/2020 00:02:33] \"POST /link_items HTTP/1.1\" 500 -"}
{"asctime": "11/06/2020 12:03:02 AM", "levelname": "ERROR", "name": "routes", "message": "Exception on /link_items [POST]", "exc_info": "Traceback (most recent call last):\n  File \"/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/flask/app.py\", line 2446, in wsgi_app\n    response = self.full_dispatch_request()\n  File \"/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/flask/app.py\", line 1951, in full_dispatch_request\n    rv = self.handle_user_exception(e)\n  File \"/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/flask_cors/extension.py\", line 165, in wrapped_function\n    return cors_after_request(app.make_response(f(*args, **kwargs)))\n  File \"/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/flask/app.py\", line 1820, in handle_user_exception\n    reraise(exc_type, exc_value, tb)\n  File \"/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/flask/_compat.py\", line 39, in reraise\n    raise value\n  File \"/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/flask/app.py\", line 1949, in full_dispatch_request\n    rv = self.dispatch_request()\n  File \"/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/flask/app.py\", line 1935, in dispatch_request\n    return self.view_functions[rule.endpoint](**req.view_args)\n  File \"/Users/ktsutter/Capstone/JamaConnectBackend/server/routes.py\", line 306, in link_items\n    data = dict(request.json)\nTypeError: 'NoneType' object is not iterable"}
{"asctime": "11/06/2020 12:03:02 AM", "levelname": "INFO", "name": "werkzeug", "message": "127.0.0.1 - - [06/Nov/2020 00:03:02] \"POST /link_items HTTP/1.1\" 500 -"}
{"asctime": "11/06/2020 12:04:02 AM", "levelname": "ERROR", "name": "routes", "message": "Exception on /link_items [POST]", "exc_info": "Traceback (most recent call last):\n  File \"/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/flask/app.py\", line 2446, in wsgi_app\n    response = self.full_dispatch_request()\n  File \"/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/flask/app.py\", line 1951, in full_dispatch_request\n    rv = self.handle_user_exception(e)\n  File \"/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/flask_cors/extension.py\", line 165, in wrapped_function\n    return cors_after_request(app.make_response(f(*args, **kwargs)))\n  File \"/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/flask/app.py\", line 1820, in handle_user_exception\n    reraise(exc_type, exc_value, tb)\n  File \"/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/flask/_compat.py\", line 39, in reraise\n    raise value\n  File \"/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/flask/app.py\", line 1949, in full_dispatch_request\n    rv = self.dispatch_request()\n  File \"/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/flask/app.py\", line 1935, in dispatch_request\n    return self.view_functions[rule.endpoint](**req.view_args)\n  File \"/Users/ktsutter/Capstone/JamaConnectBackend/server/routes.py\", line 308, in link_items\n    jira_item = data[\"jira_item\"][0]\nKeyError: 'jira_item'"}
{"asctime": "11/06/2020 12:04:02 AM", "levelname": "INFO", "name": "werkzeug", "message": "127.0.0.1 - - [06/Nov/2020 00:04:02] \"POST /link_items HTTP/1.1\" 500 -"}
{"asctime": "11/06/2020 12:05:33 AM", "levelname": "ERROR", "name": "routes", "message": "Exception on /link_items [POST]", "exc_info": "Traceback (most recent call last):\n  File \"/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/flask/app.py\", line 2446, in wsgi_app\n    response = self.full_dispatch_request()\n  File \"/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/flask/app.py\", line 1951, in full_dispatch_request\n    rv = self.handle_user_exception(e)\n  File \"/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/flask_cors/extension.py\", line 165, in wrapped_function\n    return cors_after_request(app.make_response(f(*args, **kwargs)))\n  File \"/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/flask/app.py\", line 1820, in handle_user_exception\n    reraise(exc_type, exc_value, tb)\n  File \"/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/flask/_compat.py\", line 39, in reraise\n    raise value\n  File \"/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/flask/app.py\", line 1949, in full_dispatch_request\n    rv = self.dispatch_request()\n  File \"/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/flask/app.py\", line 1935, in dispatch_request\n    return self.view_functions[rule.endpoint](**req.view_args)\n  File \"/Users/ktsutter/Capstone/JamaConnectBackend/server/routes.py\", line 328, in link_items\n    success = database.link_items(jira_item, jama_item, jira_fields, jama_fields, num_jama_fields)\n  File \"/Users/ktsutter/Capstone/JamaConnectBackend/server/database.py\", line 583, in link_items\n    items_ops.insert_into_items_table(jira_item[0], jira_item[1], jira_item[2], \"Jira\", jama_item[0], jira_item[3], \"NULL\")\nIndexError: string index out of range"}
{"asctime": "11/06/2020 12:05:33 AM", "levelname": "ERROR", "name": "routes", "message": "Exception on /link_items [POST]", "exc_info": "Traceback (most recent call last):\n  File \"/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/flask/app.py\", line 2446, in wsgi_app\n    response = self.full_dispatch_request()\n  File \"/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/flask/app.py\", line 1951, in full_dispatch_request\n    rv = self.handle_user_exception(e)\n  File \"/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/flask_cors/extension.py\", line 165, in wrapped_function\n    return cors_after_request(app.make_response(f(*args, **kwargs)))\n  File \"/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/flask/app.py\", line 1820, in handle_user_exception\n    reraise(exc_type, exc_value, tb)\n  File \"/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/flask/_compat.py\", line 39, in reraise\n    raise value\n  File \"/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/flask/app.py\", line 1949, in full_dispatch_request\n    rv = self.dispatch_request()\n  File \"/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/flask/app.py\", line 1935, in dispatch_request\n    return self.view_functions[rule.endpoint](**req.view_args)\n  File \"/Users/ktsutter/Capstone/JamaConnectBackend/server/routes.py\", line 328, in link_items\n    success = database.link_items(jira_item, jama_item, jira_fields, jama_fields, num_jama_fields)\n  File \"/Users/ktsutter/Capstone/JamaConnectBackend/server/database.py\", line 583, in link_items\n    items_ops.insert_into_items_table(jira_item[0], jira_item[1], jira_item[2], \"Jira\", jama_item[0], jira_item[3], \"NULL\")\nIndexError: string index out of range"}
{"asctime": "11/06/2020 12:05:33 AM", "levelname": "INFO", "name": "werkzeug", "message": "127.0.0.1 - - [06/Nov/2020 00:05:33] \"POST /link_items HTTP/1.1\" 500 -"}
{"asctime": "11/06/2020 12:05:33 AM", "levelname": "INFO", "name": "werkzeug", "message": "127.0.0.1 - - [06/Nov/2020 00:05:33] \"POST /link_items HTTP/1.1\" 500 -"}
{"asctime": "11/06/2020 12:06:52 AM", "levelname": "ERROR", "name": "routes", "message": "Exception on /link_items [POST]", "exc_info": "Traceback (most recent call last):\n  File \"/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/flask/app.py\", line 2446, in wsgi_app\n    response = self.full_dispatch_request()\n  File \"/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/flask/app.py\", line 1951, in full_dispatch_request\n    rv = self.handle_user_exception(e)\n  File \"/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/flask_cors/extension.py\", line 165, in wrapped_function\n    return cors_after_request(app.make_response(f(*args, **kwargs)))\n  File \"/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/flask/app.py\", line 1820, in handle_user_exception\n    reraise(exc_type, exc_value, tb)\n  File \"/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/flask/_compat.py\", line 39, in reraise\n    raise value\n  File \"/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/flask/app.py\", line 1949, in full_dispatch_request\n    rv = self.dispatch_request()\n  File \"/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/flask/app.py\", line 1935, in dispatch_request\n    return self.view_functions[rule.endpoint](**req.view_args)\n  File \"/Users/ktsutter/Capstone/JamaConnectBackend/server/routes.py\", line 308, in link_items\n    jira_item = data[\"jira_item\"][0]\nKeyError: 'jira_item'"}
{"asctime": "11/06/2020 12:06:52 AM", "levelname": "ERROR", "name": "routes", "message": "Exception on /link_items [POST]", "exc_info": "Traceback (most recent call last):\n  File \"/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/flask/app.py\", line 2446, in wsgi_app\n    response = self.full_dispatch_request()\n  File \"/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/flask/app.py\", line 1951, in full_dispatch_request\n    rv = self.handle_user_exception(e)\n  File \"/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/flask_cors/extension.py\", line 165, in wrapped_function\n    return cors_after_request(app.make_response(f(*args, **kwargs)))\n  File \"/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/flask/app.py\", line 1820, in handle_user_exception\n    reraise(exc_type, exc_value, tb)\n  File \"/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/flask/_compat.py\", line 39, in reraise\n    raise value\n  File \"/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/flask/app.py\", line 1949, in full_dispatch_request\n    rv = self.dispatch_request()\n  File \"/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/flask/app.py\", line 1935, in dispatch_request\n    return self.view_functions[rule.endpoint](**req.view_args)\n  File \"/Users/ktsutter/Capstone/JamaConnectBackend/server/routes.py\", line 308, in link_items\n    jira_item = data[\"jira_item\"][0]\nKeyError: 'jira_item'"}
{"asctime": "11/06/2020 12:06:52 AM", "levelname": "ERROR", "name": "routes", "message": "Exception on /link_items [POST]", "exc_info": "Traceback (most recent call last):\n  File \"/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/flask/app.py\", line 2446, in wsgi_app\n    response = self.full_dispatch_request()\n  File \"/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/flask/app.py\", line 1951, in full_dispatch_request\n    rv = self.handle_user_exception(e)\n  File \"/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/flask_cors/extension.py\", line 165, in wrapped_function\n    return cors_after_request(app.make_response(f(*args, **kwargs)))\n  File \"/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/flask/app.py\", line 1820, in handle_user_exception\n    reraise(exc_type, exc_value, tb)\n  File \"/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/flask/_compat.py\", line 39, in reraise\n    raise value\n  File \"/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/flask/app.py\", line 1949, in full_dispatch_request\n    rv = self.dispatch_request()\n  File \"/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/flask/app.py\", line 1935, in dispatch_request\n    return self.view_functions[rule.endpoint](**req.view_args)\n  File \"/Users/ktsutter/Capstone/JamaConnectBackend/server/routes.py\", line 308, in link_items\n    jira_item = data[\"jira_item\"][0]\nKeyError: 'jira_item'"}
{"asctime": "11/06/2020 12:06:52 AM", "levelname": "INFO", "name": "werkzeug", "message": "127.0.0.1 - - [06/Nov/2020 00:06:52] \"POST /link_items HTTP/1.1\" 500 -"}
{"asctime": "11/06/2020 12:06:52 AM", "levelname": "INFO", "name": "werkzeug", "message": "127.0.0.1 - - [06/Nov/2020 00:06:52] \"POST /link_items HTTP/1.1\" 500 -"}
{"asctime": "11/06/2020 12:06:52 AM", "levelname": "INFO", "name": "werkzeug", "message": "127.0.0.1 - - [06/Nov/2020 00:06:52] \"POST /link_items HTTP/1.1\" 500 -"}
{"asctime": "11/06/2020 12:25:33 AM", "levelname": "ERROR", "name": "routes", "message": "Exception on /link_items [POST]", "exc_info": "Traceback (most recent call last):\n  File \"/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/flask/app.py\", line 2446, in wsgi_app\n    response = self.full_dispatch_request()\n  File \"/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/flask/app.py\", line 1951, in full_dispatch_request\n    rv = self.handle_user_exception(e)\n  File \"/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/flask_cors/extension.py\", line 165, in wrapped_function\n    return cors_after_request(app.make_response(f(*args, **kwargs)))\n  File \"/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/flask/app.py\", line 1820, in handle_user_exception\n    reraise(exc_type, exc_value, tb)\n  File \"/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/flask/_compat.py\", line 39, in reraise\n    raise value\n  File \"/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/flask/app.py\", line 1949, in full_dispatch_request\n    rv = self.dispatch_request()\n  File \"/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/flask/app.py\", line 1935, in dispatch_request\n    return self.view_functions[rule.endpoint](**req.view_args)\n  File \"/Users/ktsutter/Capstone/JamaConnectBackend/server/routes.py\", line 325, in link_items\n    success = database.link_items(jira_item, jama_item, jira_fields, jama_fields, num_jama_fields)\n  File \"/Users/ktsutter/Capstone/JamaConnectBackend/server/database.py\", line 583, in link_items\n    items_ops.insert_into_items_table(jira_item[0], jira_item[1], jira_item[2], \"Jira\", jama_item[0], jira_item[3], \"NULL\")\n  File \"/Users/ktsutter/Capstone/JamaConnectBackend/server/database.py\", line 228, in insert_into_items_table\n    self.db_ops.insert_into_db(self.table_name, str(id_), title, type, service, str(linked_id), str(project_id), last_sync_time)\n  File \"/Users/ktsutter/Capstone/JamaConnectBackend/server/database.py\", line 43, in insert_into_db\n    c.execute(\"INSERT INTO \"+table_name+\" VALUES(?, ?, ?, ?, ?, ?, ?)\", (primary_key, c2, c3, c4, c5, c6, c7))\nsqlite3.OperationalError: no such table: Items"}
{"asctime": "11/06/2020 12:25:33 AM", "levelname": "INFO", "name": "werkzeug", "message": "127.0.0.1 - - [06/Nov/2020 00:25:33] \"POST /link_items HTTP/1.1\" 500 -"}
{"asctime": "11/06/2020 12:32:45 AM", "levelname": "ERROR", "name": "routes", "message": "Exception on /link_items [POST]", "exc_info": "Traceback (most recent call last):\n  File \"/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/flask/app.py\", line 2446, in wsgi_app\n    response = self.full_dispatch_request()\n  File \"/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/flask/app.py\", line 1951, in full_dispatch_request\n    rv = self.handle_user_exception(e)\n  File \"/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/flask_cors/extension.py\", line 165, in wrapped_function\n    return cors_after_request(app.make_response(f(*args, **kwargs)))\n  File \"/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/flask/app.py\", line 1820, in handle_user_exception\n    reraise(exc_type, exc_value, tb)\n  File \"/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/flask/_compat.py\", line 39, in reraise\n    raise value\n  File \"/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/flask/app.py\", line 1949, in full_dispatch_request\n    rv = self.dispatch_request()\n  File \"/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/flask/app.py\", line 1935, in dispatch_request\n    return self.view_functions[rule.endpoint](**req.view_args)\n  File \"/Users/ktsutter/Capstone/JamaConnectBackend/server/routes.py\", line 310, in link_items\n    for i in range(0, num_fields):\nTypeError: 'str' object cannot be interpreted as an integer"}
{"asctime": "11/06/2020 12:32:45 AM", "levelname": "INFO", "name": "werkzeug", "message": "127.0.0.1 - - [06/Nov/2020 00:32:45] \"POST /link_items HTTP/1.1\" 500 -"}
{"asctime": "11/06/2020 12:33:59 AM", "levelname": "ERROR", "name": "routes", "message": "Exception on /link_items [POST]", "exc_info": "Traceback (most recent call last):\n  File \"/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/flask/app.py\", line 2446, in wsgi_app\n    response = self.full_dispatch_request()\n  File \"/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/flask/app.py\", line 1951, in full_dispatch_request\n    rv = self.handle_user_exception(e)\n  File \"/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/flask_cors/extension.py\", line 165, in wrapped_function\n    return cors_after_request(app.make_response(f(*args, **kwargs)))\n  File \"/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/flask/app.py\", line 1820, in handle_user_exception\n    reraise(exc_type, exc_value, tb)\n  File \"/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/flask/_compat.py\", line 39, in reraise\n    raise value\n  File \"/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/flask/app.py\", line 1949, in full_dispatch_request\n    rv = self.dispatch_request()\n  File \"/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/flask/app.py\", line 1935, in dispatch_request\n    return self.view_functions[rule.endpoint](**req.view_args)\n  File \"/Users/ktsutter/Capstone/JamaConnectBackend/server/routes.py\", line 312, in link_items\n    for i in range(0, num_fields):\nTypeError: 'str' object cannot be interpreted as an integer"}
{"asctime": "11/06/2020 12:33:59 AM", "levelname": "INFO", "name": "werkzeug", "message": "127.0.0.1 - - [06/Nov/2020 00:33:59] \"POST /link_items HTTP/1.1\" 500 -"}
{"asctime": "11/06/2020 12:34:27 AM", "levelname": "ERROR", "name": "routes", "message": "Exception on /link_items [POST]", "exc_info": "Traceback (most recent call last):\n  File \"/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/flask/app.py\", line 2446, in wsgi_app\n    response = self.full_dispatch_request()\n  File \"/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/flask/app.py\", line 1951, in full_dispatch_request\n    rv = self.handle_user_exception(e)\n  File \"/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/flask_cors/extension.py\", line 165, in wrapped_function\n    return cors_after_request(app.make_response(f(*args, **kwargs)))\n  File \"/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/flask/app.py\", line 1820, in handle_user_exception\n    reraise(exc_type, exc_value, tb)\n  File \"/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/flask/_compat.py\", line 39, in reraise\n    raise value\n  File \"/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/flask/app.py\", line 1949, in full_dispatch_request\n    rv = self.dispatch_request()\n  File \"/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/flask/app.py\", line 1935, in dispatch_request\n    return self.view_functions[rule.endpoint](**req.view_args)\n  File \"/Users/ktsutter/Capstone/JamaConnectBackend/server/routes.py\", line 313, in link_items\n    for i in range(0, num_fields):\nTypeError: 'str' object cannot be interpreted as an integer"}
{"asctime": "11/06/2020 12:34:27 AM", "levelname": "INFO", "name": "werkzeug", "message": "127.0.0.1 - - [06/Nov/2020 00:34:27] \"POST /link_items HTTP/1.1\" 500 -"}
{"asctime": "11/06/2020 12:35:31 AM", "levelname": "ERROR", "name": "routes", "message": "Exception on /link_items [POST]", "exc_info": "Traceback (most recent call last):\n  File \"/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/flask/app.py\", line 2446, in wsgi_app\n    response = self.full_dispatch_request()\n  File \"/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/flask/app.py\", line 1951, in full_dispatch_request\n    rv = self.handle_user_exception(e)\n  File \"/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/flask_cors/extension.py\", line 165, in wrapped_function\n    return cors_after_request(app.make_response(f(*args, **kwargs)))\n  File \"/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/flask/app.py\", line 1820, in handle_user_exception\n    reraise(exc_type, exc_value, tb)\n  File \"/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/flask/_compat.py\", line 39, in reraise\n    raise value\n  File \"/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/flask/app.py\", line 1949, in full_dispatch_request\n    rv = self.dispatch_request()\n  File \"/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/flask/app.py\", line 1935, in dispatch_request\n    return self.view_functions[rule.endpoint](**req.view_args)\n  File \"/Users/ktsutter/Capstone/JamaConnectBackend/server/routes.py\", line 313, in link_items\n    for i in range(0, num_fields):\nTypeError: 'str' object cannot be interpreted as an integer"}
{"asctime": "11/06/2020 12:35:31 AM", "levelname": "INFO", "name": "werkzeug", "message": "127.0.0.1 - - [06/Nov/2020 00:35:31] \"POST /link_items HTTP/1.1\" 500 -"}
{"asctime": "11/06/2020 12:35:52 AM", "levelname": "ERROR", "name": "routes", "message": "Exception on /link_items [POST]", "exc_info": "Traceback (most recent call last):\n  File \"/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/flask/app.py\", line 2446, in wsgi_app\n    response = self.full_dispatch_request()\n  File \"/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/flask/app.py\", line 1951, in full_dispatch_request\n    rv = self.handle_user_exception(e)\n  File \"/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/flask_cors/extension.py\", line 165, in wrapped_function\n    return cors_after_request(app.make_response(f(*args, **kwargs)))\n  File \"/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/flask/app.py\", line 1820, in handle_user_exception\n    reraise(exc_type, exc_value, tb)\n  File \"/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/flask/_compat.py\", line 39, in reraise\n    raise value\n  File \"/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/flask/app.py\", line 1949, in full_dispatch_request\n    rv = self.dispatch_request()\n  File \"/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/flask/app.py\", line 1935, in dispatch_request\n    return self.view_functions[rule.endpoint](**req.view_args)\n  File \"/Users/ktsutter/Capstone/JamaConnectBackend/server/routes.py\", line 313, in link_items\n    for i in range(0, num_fields):\nTypeError: 'str' object cannot be interpreted as an integer"}
{"asctime": "11/06/2020 12:35:52 AM", "levelname": "INFO", "name": "werkzeug", "message": "127.0.0.1 - - [06/Nov/2020 00:35:52] \"POST /link_items HTTP/1.1\" 500 -"}
{"asctime": "11/06/2020 12:36:06 AM", "levelname": "ERROR", "name": "routes", "message": "Exception on /link_items [POST]", "exc_info": "Traceback (most recent call last):\n  File \"/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/flask/app.py\", line 2446, in wsgi_app\n    response = self.full_dispatch_request()\n  File \"/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/flask/app.py\", line 1951, in full_dispatch_request\n    rv = self.handle_user_exception(e)\n  File \"/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/flask_cors/extension.py\", line 165, in wrapped_function\n    return cors_after_request(app.make_response(f(*args, **kwargs)))\n  File \"/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/flask/app.py\", line 1820, in handle_user_exception\n    reraise(exc_type, exc_value, tb)\n  File \"/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/flask/_compat.py\", line 39, in reraise\n    raise value\n  File \"/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/flask/app.py\", line 1949, in full_dispatch_request\n    rv = self.dispatch_request()\n  File \"/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/flask/app.py\", line 1935, in dispatch_request\n    return self.view_functions[rule.endpoint](**req.view_args)\n  File \"/Users/ktsutter/Capstone/JamaConnectBackend/server/routes.py\", line 313, in link_items\n    for i in range(0, num_fields):\nTypeError: 'str' object cannot be interpreted as an integer"}
{"asctime": "11/06/2020 12:36:06 AM", "levelname": "ERROR", "name": "routes", "message": "Exception on /link_items [POST]", "exc_info": "Traceback (most recent call last):\n  File \"/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/flask/app.py\", line 2446, in wsgi_app\n    response = self.full_dispatch_request()\n  File \"/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/flask/app.py\", line 1951, in full_dispatch_request\n    rv = self.handle_user_exception(e)\n  File \"/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/flask_cors/extension.py\", line 165, in wrapped_function\n    return cors_after_request(app.make_response(f(*args, **kwargs)))\n  File \"/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/flask/app.py\", line 1820, in handle_user_exception\n    reraise(exc_type, exc_value, tb)\n  File \"/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/flask/_compat.py\", line 39, in reraise\n    raise value\n  File \"/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/flask/app.py\", line 1949, in full_dispatch_request\n    rv = self.dispatch_request()\n  File \"/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/flask/app.py\", line 1935, in dispatch_request\n    return self.view_functions[rule.endpoint](**req.view_args)\n  File \"/Users/ktsutter/Capstone/JamaConnectBackend/server/routes.py\", line 313, in link_items\n    for i in range(0, num_fields):\nTypeError: 'str' object cannot be interpreted as an integer"}
{"asctime": "11/06/2020 12:36:06 AM", "levelname": "INFO", "name": "werkzeug", "message": "127.0.0.1 - - [06/Nov/2020 00:36:06] \"POST /link_items HTTP/1.1\" 500 -"}
{"asctime": "11/06/2020 12:36:06 AM", "levelname": "INFO", "name": "werkzeug", "message": "127.0.0.1 - - [06/Nov/2020 00:36:06] \"POST /link_items HTTP/1.1\" 500 -"}
{"asctime": "11/06/2020 12:36:36 AM", "levelname": "ERROR", "name": "routes", "message": "Exception on /link_items [POST]", "exc_info": "Traceback (most recent call last):\n  File \"/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/flask/app.py\", line 2446, in wsgi_app\n    response = self.full_dispatch_request()\n  File \"/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/flask/app.py\", line 1951, in full_dispatch_request\n    rv = self.handle_user_exception(e)\n  File \"/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/flask_cors/extension.py\", line 165, in wrapped_function\n    return cors_after_request(app.make_response(f(*args, **kwargs)))\n  File \"/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/flask/app.py\", line 1820, in handle_user_exception\n    reraise(exc_type, exc_value, tb)\n  File \"/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/flask/_compat.py\", line 39, in reraise\n    raise value\n  File \"/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/flask/app.py\", line 1949, in full_dispatch_request\n    rv = self.dispatch_request()\n  File \"/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/flask/app.py\", line 1935, in dispatch_request\n    return self.view_functions[rule.endpoint](**req.view_args)\n  File \"/Users/ktsutter/Capstone/JamaConnectBackend/server/routes.py\", line 314, in link_items\n    for i in range(0, num_fields):\nTypeError: 'str' object cannot be interpreted as an integer"}
{"asctime": "11/06/2020 12:36:36 AM", "levelname": "INFO", "name": "werkzeug", "message": "127.0.0.1 - - [06/Nov/2020 00:36:36] \"POST /link_items HTTP/1.1\" 500 -"}
{"asctime": "11/06/2020 12:39:41 AM", "levelname": "ERROR", "name": "routes", "message": "Exception on /link_items [POST]", "exc_info": "Traceback (most recent call last):\n  File \"/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/flask/app.py\", line 2446, in wsgi_app\n    response = self.full_dispatch_request()\n  File \"/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/flask/app.py\", line 1951, in full_dispatch_request\n    rv = self.handle_user_exception(e)\n  File \"/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/flask_cors/extension.py\", line 165, in wrapped_function\n    return cors_after_request(app.make_response(f(*args, **kwargs)))\n  File \"/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/flask/app.py\", line 1820, in handle_user_exception\n    reraise(exc_type, exc_value, tb)\n  File \"/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/flask/_compat.py\", line 39, in reraise\n    raise value\n  File \"/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/flask/app.py\", line 1949, in full_dispatch_request\n    rv = self.dispatch_request()\n  File \"/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/flask/app.py\", line 1935, in dispatch_request\n    return self.view_functions[rule.endpoint](**req.view_args)\n  File \"/Users/ktsutter/Capstone/JamaConnectBackend/server/routes.py\", line 313, in link_items\n    for i in range(0, num_fields):\nTypeError: 'str' object cannot be interpreted as an integer"}
{"asctime": "11/06/2020 12:39:41 AM", "levelname": "INFO", "name": "werkzeug", "message": "127.0.0.1 - - [06/Nov/2020 00:39:41] \"POST /link_items HTTP/1.1\" 500 -"}
{"asctime": "11/06/2020 12:41:37 AM", "levelname": "ERROR", "name": "routes", "message": "Exception on /link_items [POST]", "exc_info": "Traceback (most recent call last):\n  File \"/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/flask/app.py\", line 2446, in wsgi_app\n    response = self.full_dispatch_request()\n  File \"/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/flask/app.py\", line 1951, in full_dispatch_request\n    rv = self.handle_user_exception(e)\n  File \"/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/flask_cors/extension.py\", line 165, in wrapped_function\n    return cors_after_request(app.make_response(f(*args, **kwargs)))\n  File \"/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/flask/app.py\", line 1820, in handle_user_exception\n    reraise(exc_type, exc_value, tb)\n  File \"/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/flask/_compat.py\", line 39, in reraise\n    raise value\n  File \"/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/flask/app.py\", line 1949, in full_dispatch_request\n    rv = self.dispatch_request()\n  File \"/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/flask/app.py\", line 1935, in dispatch_request\n    return self.view_functions[rule.endpoint](**req.view_args)\n  File \"/Users/ktsutter/Capstone/JamaConnectBackend/server/routes.py\", line 313, in link_items\n    for i in range(0, num_fields):\nTypeError: 'str' object cannot be interpreted as an integer"}
{"asctime": "11/06/2020 12:41:37 AM", "levelname": "INFO", "name": "werkzeug", "message": "127.0.0.1 - - [06/Nov/2020 00:41:37] \"POST /link_items HTTP/1.1\" 500 -"}
{"asctime": "11/06/2020 12:42:02 AM", "levelname": "ERROR", "name": "routes", "message": "Exception on /link_items [POST]", "exc_info": "Traceback (most recent call last):\n  File \"/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/flask/app.py\", line 2446, in wsgi_app\n    response = self.full_dispatch_request()\n  File \"/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/flask/app.py\", line 1951, in full_dispatch_request\n    rv = self.handle_user_exception(e)\n  File \"/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/flask_cors/extension.py\", line 165, in wrapped_function\n    return cors_after_request(app.make_response(f(*args, **kwargs)))\n  File \"/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/flask/app.py\", line 1820, in handle_user_exception\n    reraise(exc_type, exc_value, tb)\n  File \"/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/flask/_compat.py\", line 39, in reraise\n    raise value\n  File \"/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/flask/app.py\", line 1949, in full_dispatch_request\n    rv = self.dispatch_request()\n  File \"/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/flask/app.py\", line 1935, in dispatch_request\n    return self.view_functions[rule.endpoint](**req.view_args)\n  File \"/Users/ktsutter/Capstone/JamaConnectBackend/server/routes.py\", line 313, in link_items\n    for i in range(0, num_fields):\nTypeError: 'str' object cannot be interpreted as an integer"}
{"asctime": "11/06/2020 12:42:02 AM", "levelname": "INFO", "name": "werkzeug", "message": "127.0.0.1 - - [06/Nov/2020 00:42:02] \"POST /link_items HTTP/1.1\" 500 -"}
{"asctime": "11/06/2020 12:44:36 AM", "levelname": "ERROR", "name": "routes", "message": "Exception on /link_items [POST]", "exc_info": "Traceback (most recent call last):\n  File \"/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/flask/app.py\", line 2446, in wsgi_app\n    response = self.full_dispatch_request()\n  File \"/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/flask/app.py\", line 1951, in full_dispatch_request\n    rv = self.handle_user_exception(e)\n  File \"/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/flask_cors/extension.py\", line 165, in wrapped_function\n    return cors_after_request(app.make_response(f(*args, **kwargs)))\n  File \"/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/flask/app.py\", line 1820, in handle_user_exception\n    reraise(exc_type, exc_value, tb)\n  File \"/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/flask/_compat.py\", line 39, in reraise\n    raise value\n  File \"/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/flask/app.py\", line 1949, in full_dispatch_request\n    rv = self.dispatch_request()\n  File \"/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/flask/app.py\", line 1935, in dispatch_request\n    return self.view_functions[rule.endpoint](**req.view_args)\n  File \"/Users/ktsutter/Capstone/JamaConnectBackend/server/routes.py\", line 313, in link_items\n    for i in range(0, num_fields):\nTypeError: 'str' object cannot be interpreted as an integer"}
{"asctime": "11/06/2020 12:44:36 AM", "levelname": "INFO", "name": "werkzeug", "message": "127.0.0.1 - - [06/Nov/2020 00:44:36] \"POST /link_items HTTP/1.1\" 500 -"}
{"asctime": "11/06/2020 12:44:58 AM", "levelname": "ERROR", "name": "routes", "message": "Exception on /link_items [POST]", "exc_info": "Traceback (most recent call last):\n  File \"/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/flask/app.py\", line 2446, in wsgi_app\n    response = self.full_dispatch_request()\n  File \"/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/flask/app.py\", line 1951, in full_dispatch_request\n    rv = self.handle_user_exception(e)\n  File \"/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/flask_cors/extension.py\", line 165, in wrapped_function\n    return cors_after_request(app.make_response(f(*args, **kwargs)))\n  File \"/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/flask/app.py\", line 1820, in handle_user_exception\n    reraise(exc_type, exc_value, tb)\n  File \"/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/flask/_compat.py\", line 39, in reraise\n    raise value\n  File \"/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/flask/app.py\", line 1949, in full_dispatch_request\n    rv = self.dispatch_request()\n  File \"/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/flask/app.py\", line 1935, in dispatch_request\n    return self.view_functions[rule.endpoint](**req.view_args)\n  File \"/Users/ktsutter/Capstone/JamaConnectBackend/server/routes.py\", line 313, in link_items\n    for i in range(0, num_fields):\nTypeError: 'str' object cannot be interpreted as an integer"}
{"asctime": "11/06/2020 12:44:58 AM", "levelname": "INFO", "name": "werkzeug", "message": "127.0.0.1 - - [06/Nov/2020 00:44:58] \"POST /link_items HTTP/1.1\" 500 -"}
{"asctime": "11/06/2020 12:45:52 AM", "levelname": "ERROR", "name": "routes", "message": "Exception on /link_items [POST]", "exc_info": "Traceback (most recent call last):\n  File \"/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/flask/app.py\", line 2446, in wsgi_app\n    response = self.full_dispatch_request()\n  File \"/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/flask/app.py\", line 1951, in full_dispatch_request\n    rv = self.handle_user_exception(e)\n  File \"/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/flask_cors/extension.py\", line 165, in wrapped_function\n    return cors_after_request(app.make_response(f(*args, **kwargs)))\n  File \"/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/flask/app.py\", line 1820, in handle_user_exception\n    reraise(exc_type, exc_value, tb)\n  File \"/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/flask/_compat.py\", line 39, in reraise\n    raise value\n  File \"/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/flask/app.py\", line 1949, in full_dispatch_request\n    rv = self.dispatch_request()\n  File \"/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/flask/app.py\", line 1935, in dispatch_request\n    return self.view_functions[rule.endpoint](**req.view_args)\n  File \"/Users/ktsutter/Capstone/JamaConnectBackend/server/routes.py\", line 331, in link_items\n    success = database.link_items(jira_item, jama_item, jira_fields, jama_fields, num_jama_fields)\n  File \"/Users/ktsutter/Capstone/JamaConnectBackend/server/database.py\", line 583, in link_items\n    items_ops.insert_into_items_table(jira_item[0], jira_item[1], jira_item[2], \"Jira\", jama_item[0], jira_item[3], \"NULL\")\n  File \"/Users/ktsutter/Capstone/JamaConnectBackend/server/database.py\", line 228, in insert_into_items_table\n    self.db_ops.insert_into_db(self.table_name, str(id_), title, type, service, str(linked_id), str(project_id), last_sync_time)\n  File \"/Users/ktsutter/Capstone/JamaConnectBackend/server/database.py\", line 43, in insert_into_db\n    c.execute(\"INSERT INTO \"+table_name+\" VALUES(?, ?, ?, ?, ?, ?, ?)\", (primary_key, c2, c3, c4, c5, c6, c7))\nsqlite3.OperationalError: no such table: Items"}
{"asctime": "11/06/2020 12:45:52 AM", "levelname": "INFO", "name": "werkzeug", "message": "127.0.0.1 - - [06/Nov/2020 00:45:52] \"POST /link_items HTTP/1.1\" 500 -"}
{"asctime": "11/06/2020 12:49:45 AM", "levelname": "ERROR", "name": "routes", "message": "Exception on /link_items [POST]", "exc_info": "Traceback (most recent call last):\n  File \"/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/flask/app.py\", line 2446, in wsgi_app\n    response = self.full_dispatch_request()\n  File \"/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/flask/app.py\", line 1951, in full_dispatch_request\n    rv = self.handle_user_exception(e)\n  File \"/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/flask_cors/extension.py\", line 165, in wrapped_function\n    return cors_after_request(app.make_response(f(*args, **kwargs)))\n  File \"/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/flask/app.py\", line 1820, in handle_user_exception\n    reraise(exc_type, exc_value, tb)\n  File \"/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/flask/_compat.py\", line 39, in reraise\n    raise value\n  File \"/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/flask/app.py\", line 1949, in full_dispatch_request\n    rv = self.dispatch_request()\n  File \"/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/flask/app.py\", line 1935, in dispatch_request\n    return self.view_functions[rule.endpoint](**req.view_args)\n  File \"/Users/ktsutter/Capstone/JamaConnectBackend/server/routes.py\", line 331, in link_items\n    return {\"error\": \"The number of Jama fields to link does not match the number of Jira fields.\"}, 500\n  File \"/Users/ktsutter/Capstone/JamaConnectBackend/server/database.py\", line 583, in link_items\n    items_ops.insert_into_items_table(jira_item[0], jira_item[1], jira_item[2], \"Jira\", jama_item[0], jira_item[3], \"NULL\")\n  File \"/Users/ktsutter/Capstone/JamaConnectBackend/server/database.py\", line 228, in insert_into_items_table\n    self.db_ops.insert_into_db(self.table_name, str(id_), title, type, service, str(linked_id), str(project_id), last_sync_time)\n  File \"/Users/ktsutter/Capstone/JamaConnectBackend/server/database.py\", line 43, in insert_into_db\n    c.execute(\"INSERT INTO \"+table_name+\" VALUES(?, ?, ?, ?, ?, ?, ?)\", (primary_key, c2, c3, c4, c5, c6, c7))\nsqlite3.OperationalError: no such table: Items"}
{"asctime": "11/06/2020 12:49:45 AM", "levelname": "ERROR", "name": "routes", "message": "Exception on /link_items [POST]", "exc_info": "Traceback (most recent call last):\n  File \"/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/flask/app.py\", line 2446, in wsgi_app\n    response = self.full_dispatch_request()\n  File \"/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/flask/app.py\", line 1951, in full_dispatch_request\n    rv = self.handle_user_exception(e)\n  File \"/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/flask_cors/extension.py\", line 165, in wrapped_function\n    return cors_after_request(app.make_response(f(*args, **kwargs)))\n  File \"/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/flask/app.py\", line 1820, in handle_user_exception\n    reraise(exc_type, exc_value, tb)\n  File \"/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/flask/_compat.py\", line 39, in reraise\n    raise value\n  File \"/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/flask/app.py\", line 1949, in full_dispatch_request\n    rv = self.dispatch_request()\n  File \"/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/flask/app.py\", line 1935, in dispatch_request\n    return self.view_functions[rule.endpoint](**req.view_args)\n  File \"/Users/ktsutter/Capstone/JamaConnectBackend/server/routes.py\", line 331, in link_items\n    return {\"error\": \"The number of Jama fields to link does not match the number of Jira fields.\"}, 500\n  File \"/Users/ktsutter/Capstone/JamaConnectBackend/server/database.py\", line 583, in link_items\n    items_ops.insert_into_items_table(jira_item[0], jira_item[1], jira_item[2], \"Jira\", jama_item[0], jira_item[3], \"NULL\")\n  File \"/Users/ktsutter/Capstone/JamaConnectBackend/server/database.py\", line 228, in insert_into_items_table\n    self.db_ops.insert_into_db(self.table_name, str(id_), title, type, service, str(linked_id), str(project_id), last_sync_time)\n  File \"/Users/ktsutter/Capstone/JamaConnectBackend/server/database.py\", line 43, in insert_into_db\n    c.execute(\"INSERT INTO \"+table_name+\" VALUES(?, ?, ?, ?, ?, ?, ?)\", (primary_key, c2, c3, c4, c5, c6, c7))\nsqlite3.OperationalError: no such table: Items"}
{"asctime": "11/06/2020 12:49:45 AM", "levelname": "INFO", "name": "werkzeug", "message": "127.0.0.1 - - [06/Nov/2020 00:49:45] \"POST /link_items HTTP/1.1\" 500 -"}
{"asctime": "11/06/2020 12:49:45 AM", "levelname": "INFO", "name": "werkzeug", "message": "127.0.0.1 - - [06/Nov/2020 00:49:45] \"POST /link_items HTTP/1.1\" 500 -"}
{"asctime": "11/06/2020 12:50:41 AM", "levelname": "ERROR", "name": "routes", "message": "Exception on /link_items [POST]", "exc_info": "Traceback (most recent call last):\n  File \"/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/flask/app.py\", line 2446, in wsgi_app\n    response = self.full_dispatch_request()\n  File \"/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/flask/app.py\", line 1951, in full_dispatch_request\n    rv = self.handle_user_exception(e)\n  File \"/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/flask_cors/extension.py\", line 165, in wrapped_function\n    return cors_after_request(app.make_response(f(*args, **kwargs)))\n  File \"/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/flask/app.py\", line 1820, in handle_user_exception\n    reraise(exc_type, exc_value, tb)\n  File \"/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/flask/_compat.py\", line 39, in reraise\n    raise value\n  File \"/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/flask/app.py\", line 1949, in full_dispatch_request\n    rv = self.dispatch_request()\n  File \"/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/flask/app.py\", line 1935, in dispatch_request\n    return self.view_functions[rule.endpoint](**req.view_args)\n  File \"/Users/ktsutter/Capstone/JamaConnectBackend/server/routes.py\", line 331, in link_items\n    return {\"error\": \"The number of Jama fields to link does not match the number of Jira fields.\"}, 500\n  File \"/Users/ktsutter/Capstone/JamaConnectBackend/server/database.py\", line 583, in link_items\n    items_ops.insert_into_items_table(jira_item[0], jira_item[1], jira_item[2], \"Jira\", jama_item[0], jira_item[3], \"NULL\")\n  File \"/Users/ktsutter/Capstone/JamaConnectBackend/server/database.py\", line 228, in insert_into_items_table\n    self.db_ops.insert_into_db(self.table_name, str(id_), title, type, service, str(linked_id), str(project_id), last_sync_time)\n  File \"/Users/ktsutter/Capstone/JamaConnectBackend/server/database.py\", line 43, in insert_into_db\n    c.execute(\"INSERT INTO \"+table_name+\" VALUES(?, ?, ?, ?, ?, ?, ?)\", (primary_key, c2, c3, c4, c5, c6, c7))\nsqlite3.OperationalError: no such table: Items"}
{"asctime": "11/06/2020 12:50:41 AM", "levelname": "ERROR", "name": "routes", "message": "Exception on /link_items [POST]", "exc_info": "Traceback (most recent call last):\n  File \"/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/flask/app.py\", line 2446, in wsgi_app\n    response = self.full_dispatch_request()\n  File \"/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/flask/app.py\", line 1951, in full_dispatch_request\n    rv = self.handle_user_exception(e)\n  File \"/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/flask_cors/extension.py\", line 165, in wrapped_function\n    return cors_after_request(app.make_response(f(*args, **kwargs)))\n  File \"/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/flask/app.py\", line 1820, in handle_user_exception\n    reraise(exc_type, exc_value, tb)\n  File \"/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/flask/_compat.py\", line 39, in reraise\n    raise value\n  File \"/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/flask/app.py\", line 1949, in full_dispatch_request\n    rv = self.dispatch_request()\n  File \"/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/flask/app.py\", line 1935, in dispatch_request\n    return self.view_functions[rule.endpoint](**req.view_args)\n  File \"/Users/ktsutter/Capstone/JamaConnectBackend/server/routes.py\", line 331, in link_items\n    return {\"error\": \"The number of Jama fields to link does not match the number of Jira fields.\"}, 500\n  File \"/Users/ktsutter/Capstone/JamaConnectBackend/server/database.py\", line 583, in link_items\n    items_ops.insert_into_items_table(jira_item[0], jira_item[1], jira_item[2], \"Jira\", jama_item[0], jira_item[3], \"NULL\")\n  File \"/Users/ktsutter/Capstone/JamaConnectBackend/server/database.py\", line 228, in insert_into_items_table\n    self.db_ops.insert_into_db(self.table_name, str(id_), title, type, service, str(linked_id), str(project_id), last_sync_time)\n  File \"/Users/ktsutter/Capstone/JamaConnectBackend/server/database.py\", line 43, in insert_into_db\n    c.execute(\"INSERT INTO \"+table_name+\" VALUES(?, ?, ?, ?, ?, ?, ?)\", (primary_key, c2, c3, c4, c5, c6, c7))\nsqlite3.OperationalError: no such table: Items"}
{"asctime": "11/06/2020 12:50:41 AM", "levelname": "ERROR", "name": "routes", "message": "Exception on /link_items [POST]", "exc_info": "Traceback (most recent call last):\n  File \"/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/flask/app.py\", line 2446, in wsgi_app\n    response = self.full_dispatch_request()\n  File \"/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/flask/app.py\", line 1951, in full_dispatch_request\n    rv = self.handle_user_exception(e)\n  File \"/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/flask_cors/extension.py\", line 165, in wrapped_function\n    return cors_after_request(app.make_response(f(*args, **kwargs)))\n  File \"/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/flask/app.py\", line 1820, in handle_user_exception\n    reraise(exc_type, exc_value, tb)\n  File \"/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/flask/_compat.py\", line 39, in reraise\n    raise value\n  File \"/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/flask/app.py\", line 1949, in full_dispatch_request\n    rv = self.dispatch_request()\n  File \"/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/flask/app.py\", line 1935, in dispatch_request\n    return self.view_functions[rule.endpoint](**req.view_args)\n  File \"/Users/ktsutter/Capstone/JamaConnectBackend/server/routes.py\", line 331, in link_items\n    return {\"error\": \"The number of Jama fields to link does not match the number of Jira fields.\"}, 500\n  File \"/Users/ktsutter/Capstone/JamaConnectBackend/server/database.py\", line 583, in link_items\n    items_ops.insert_into_items_table(jira_item[0], jira_item[1], jira_item[2], \"Jira\", jama_item[0], jira_item[3], \"NULL\")\n  File \"/Users/ktsutter/Capstone/JamaConnectBackend/server/database.py\", line 228, in insert_into_items_table\n    self.db_ops.insert_into_db(self.table_name, str(id_), title, type, service, str(linked_id), str(project_id), last_sync_time)\n  File \"/Users/ktsutter/Capstone/JamaConnectBackend/server/database.py\", line 43, in insert_into_db\n    c.execute(\"INSERT INTO \"+table_name+\" VALUES(?, ?, ?, ?, ?, ?, ?)\", (primary_key, c2, c3, c4, c5, c6, c7))\nsqlite3.OperationalError: no such table: Items"}
{"asctime": "11/06/2020 12:50:41 AM", "levelname": "INFO", "name": "werkzeug", "message": "127.0.0.1 - - [06/Nov/2020 00:50:41] \"POST /link_items HTTP/1.1\" 500 -"}
{"asctime": "11/06/2020 12:50:41 AM", "levelname": "INFO", "name": "werkzeug", "message": "127.0.0.1 - - [06/Nov/2020 00:50:41] \"POST /link_items HTTP/1.1\" 500 -"}
{"asctime": "11/06/2020 12:50:41 AM", "levelname": "INFO", "name": "werkzeug", "message": "127.0.0.1 - - [06/Nov/2020 00:50:41] \"POST /link_items HTTP/1.1\" 500 -"}
{"asctime": "11/06/2020 12:51:58 AM", "levelname": "ERROR", "name": "routes", "message": "Exception on /link_items [POST]", "exc_info": "Traceback (most recent call last):\n  File \"/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/flask/app.py\", line 2446, in wsgi_app\n    response = self.full_dispatch_request()\n  File \"/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/flask/app.py\", line 1951, in full_dispatch_request\n    rv = self.handle_user_exception(e)\n  File \"/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/flask_cors/extension.py\", line 165, in wrapped_function\n    return cors_after_request(app.make_response(f(*args, **kwargs)))\n  File \"/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/flask/app.py\", line 1820, in handle_user_exception\n    reraise(exc_type, exc_value, tb)\n  File \"/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/flask/_compat.py\", line 39, in reraise\n    raise value\n  File \"/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/flask/app.py\", line 1949, in full_dispatch_request\n    rv = self.dispatch_request()\n  File \"/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/flask/app.py\", line 1935, in dispatch_request\n    return self.view_functions[rule.endpoint](**req.view_args)\n  File \"/Users/ktsutter/Capstone/JamaConnectBackend/server/routes.py\", line 332, in link_items\n    success = database.link_items(jira_item, jama_item, jira_fields, jama_fields, num_jama_fields)\n  File \"/Users/ktsutter/Capstone/JamaConnectBackend/server/database.py\", line 583, in link_items\n    items_ops.insert_into_items_table(jira_item[0], jira_item[1], jira_item[2], \"Jira\", jama_item[0], jira_item[3], \"NULL\")\n  File \"/Users/ktsutter/Capstone/JamaConnectBackend/server/database.py\", line 228, in insert_into_items_table\n    self.db_ops.insert_into_db(self.table_name, str(id_), title, type, service, str(linked_id), str(project_id), last_sync_time)\n  File \"/Users/ktsutter/Capstone/JamaConnectBackend/server/database.py\", line 43, in insert_into_db\n    c.execute(\"INSERT INTO \"+table_name+\" VALUES(?, ?, ?, ?, ?, ?, ?)\", (primary_key, c2, c3, c4, c5, c6, c7))\nsqlite3.OperationalError: no such table: Items"}
{"asctime": "11/06/2020 12:51:58 AM", "levelname": "INFO", "name": "werkzeug", "message": "127.0.0.1 - - [06/Nov/2020 00:51:58] \"POST /link_items HTTP/1.1\" 500 -"}
{"asctime": "11/06/2020 12:53:53 AM", "levelname": "ERROR", "name": "routes", "message": "Exception on /link_items [POST]", "exc_info": "Traceback (most recent call last):\n  File \"/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/flask/app.py\", line 2446, in wsgi_app\n    response = self.full_dispatch_request()\n  File \"/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/flask/app.py\", line 1951, in full_dispatch_request\n    rv = self.handle_user_exception(e)\n  File \"/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/flask_cors/extension.py\", line 165, in wrapped_function\n    return cors_after_request(app.make_response(f(*args, **kwargs)))\n  File \"/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/flask/app.py\", line 1820, in handle_user_exception\n    reraise(exc_type, exc_value, tb)\n  File \"/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/flask/_compat.py\", line 39, in reraise\n    raise value\n  File \"/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/flask/app.py\", line 1949, in full_dispatch_request\n    rv = self.dispatch_request()\n  File \"/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/flask/app.py\", line 1935, in dispatch_request\n    return self.view_functions[rule.endpoint](**req.view_args)\n  File \"/Users/ktsutter/Capstone/JamaConnectBackend/server/routes.py\", line 332, in link_items\n    success = database.link_items(jira_item, jama_item, jira_fields, jama_fields, num_jama_fields)\n  File \"/Users/ktsutter/Capstone/JamaConnectBackend/server/database.py\", line 583, in link_items\n    items_ops.insert_into_items_table(jira_item[0], jira_item[1], jira_item[2], \"Jira\", jama_item[0], jira_item[3], \"NULL\")\n  File \"/Users/ktsutter/Capstone/JamaConnectBackend/server/database.py\", line 228, in insert_into_items_table\n    self.db_ops.insert_into_db(self.table_name, str(id_), title, type, service, str(linked_id), str(project_id), last_sync_time)\n  File \"/Users/ktsutter/Capstone/JamaConnectBackend/server/database.py\", line 43, in insert_into_db\n    c.execute(\"INSERT INTO \"+table_name+\" VALUES(?, ?, ?, ?, ?, ?, ?)\", (primary_key, c2, c3, c4, c5, c6, c7))\nsqlite3.OperationalError: no such table: Items"}
{"asctime": "11/06/2020 12:53:53 AM", "levelname": "ERROR", "name": "routes", "message": "Exception on /link_items [POST]", "exc_info": "Traceback (most recent call last):\n  File \"/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/flask/app.py\", line 2446, in wsgi_app\n    response = self.full_dispatch_request()\n  File \"/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/flask/app.py\", line 1951, in full_dispatch_request\n    rv = self.handle_user_exception(e)\n  File \"/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/flask_cors/extension.py\", line 165, in wrapped_function\n    return cors_after_request(app.make_response(f(*args, **kwargs)))\n  File \"/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/flask/app.py\", line 1820, in handle_user_exception\n    reraise(exc_type, exc_value, tb)\n  File \"/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/flask/_compat.py\", line 39, in reraise\n    raise value\n  File \"/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/flask/app.py\", line 1949, in full_dispatch_request\n    rv = self.dispatch_request()\n  File \"/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/flask/app.py\", line 1935, in dispatch_request\n    return self.view_functions[rule.endpoint](**req.view_args)\n  File \"/Users/ktsutter/Capstone/JamaConnectBackend/server/routes.py\", line 332, in link_items\n    success = database.link_items(jira_item, jama_item, jira_fields, jama_fields, num_jama_fields)\n  File \"/Users/ktsutter/Capstone/JamaConnectBackend/server/database.py\", line 583, in link_items\n    items_ops.insert_into_items_table(jira_item[0], jira_item[1], jira_item[2], \"Jira\", jama_item[0], jira_item[3], \"NULL\")\n  File \"/Users/ktsutter/Capstone/JamaConnectBackend/server/database.py\", line 228, in insert_into_items_table\n    self.db_ops.insert_into_db(self.table_name, str(id_), title, type, service, str(linked_id), str(project_id), last_sync_time)\n  File \"/Users/ktsutter/Capstone/JamaConnectBackend/server/database.py\", line 43, in insert_into_db\n    c.execute(\"INSERT INTO \"+table_name+\" VALUES(?, ?, ?, ?, ?, ?, ?)\", (primary_key, c2, c3, c4, c5, c6, c7))\nsqlite3.OperationalError: no such table: Items"}
{"asctime": "11/06/2020 12:53:53 AM", "levelname": "INFO", "name": "werkzeug", "message": "127.0.0.1 - - [06/Nov/2020 00:53:53] \"POST /link_items HTTP/1.1\" 500 -"}
{"asctime": "11/06/2020 12:53:53 AM", "levelname": "INFO", "name": "werkzeug", "message": "127.0.0.1 - - [06/Nov/2020 00:53:53] \"POST /link_items HTTP/1.1\" 500 -"}
{"asctime": "11/06/2020 12:56:09 AM", "levelname": "ERROR", "name": "routes", "message": "Exception on /link_items [POST]", "exc_info": "Traceback (most recent call last):\n  File \"/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/flask/app.py\", line 2446, in wsgi_app\n    response = self.full_dispatch_request()\n  File \"/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/flask/app.py\", line 1951, in full_dispatch_request\n    rv = self.handle_user_exception(e)\n  File \"/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/flask_cors/extension.py\", line 165, in wrapped_function\n    return cors_after_request(app.make_response(f(*args, **kwargs)))\n  File \"/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/flask/app.py\", line 1820, in handle_user_exception\n    reraise(exc_type, exc_value, tb)\n  File \"/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/flask/_compat.py\", line 39, in reraise\n    raise value\n  File \"/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/flask/app.py\", line 1949, in full_dispatch_request\n    rv = self.dispatch_request()\n  File \"/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/flask/app.py\", line 1935, in dispatch_request\n    return self.view_functions[rule.endpoint](**req.view_args)\n  File \"/Users/ktsutter/Capstone/JamaConnectBackend/server/routes.py\", line 332, in link_items\n    success = database.link_items(jira_item, jama_item, jira_fields, jama_fields, num_jama_fields)\n  File \"/Users/ktsutter/Capstone/JamaConnectBackend/server/database.py\", line 584, in link_items\n    items_ops.insert_into_items_table(jira_item[0], jira_item[1], jira_item[2], \"Jira\", jama_item[0], jira_item[3], \"NULL\")\n  File \"/Users/ktsutter/Capstone/JamaConnectBackend/server/database.py\", line 228, in insert_into_items_table\n    self.db_ops.insert_into_db(self.table_name, str(id_), title, type, service, str(linked_id), str(project_id), last_sync_time)\n  File \"/Users/ktsutter/Capstone/JamaConnectBackend/server/database.py\", line 43, in insert_into_db\n    c.execute(\"INSERT INTO \"+table_name+\" VALUES(?, ?, ?, ?, ?, ?, ?)\", (primary_key, c2, c3, c4, c5, c6, c7))\nsqlite3.OperationalError: no such table: Items"}
{"asctime": "11/06/2020 12:56:09 AM", "levelname": "INFO", "name": "werkzeug", "message": "127.0.0.1 - - [06/Nov/2020 00:56:09] \"POST /link_items HTTP/1.1\" 500 -"}
{"asctime": "11/06/2020 12:57:38 AM", "levelname": "INFO", "name": "werkzeug", "message": "127.0.0.1 - - [06/Nov/2020 00:57:38] \"POST /link_items HTTP/1.1\" 200 -"}
